### ISSUE TITLE
Tag new version?

### ISSUE THREAD

**Issue by gfontenot** [robrix/Box#16]
Since `Box` now has an iOS scheme in addition to the OS X scheme (and the deployment target for OS X has been lowered), should we have a new tagged version?

**Comment by robrix** [comment]
:+1:

**Comment by robrix** [comment]
I’ve added you as a collaborator—don’t feel obligated to tag, but … empowered? :grin:

**Comment by gfontenot** [comment]
Ha. Handy. Thanks. Have a preferred version number? 1.1.0?

**Comment by robrix** [comment]
:+1:

**Comment by robrix** [comment]
Actually, if semver doesn’t require the .0, just 1.1 will do.

**Comment by gfontenot** [comment]
According to http://semver.org: 

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

so 1.1.0 it is.

Fixed in #17

**Comment by robrix** [comment]
:ok_hand:

**Comment by robrix** [comment]
(And thank you!)
