### ISSUE TITLE
Swift 2 protocols renamed

### ISSUE THREAD

**Issue by philipengberg** [robrix/Box#28]
When building with base SDK set to iOS 9, build errors arise since `Printable` has been renamed to `CustomStringConvertible` and `toString` to `String`.

**Comment by clarisli** [comment]
I am getting the following errors

Box.swift:6:37: error: 'Printable' has been renamed to 'CustomStringConvertible'
Box.swift:31:10: error: 'toString' has been renamed to 'String'
Box/MutableBox.swift:8:51: error: 'Printable' has been renamed to 'CustomStringConvertible'
MutableBox.swift:25:10: error: 'toString' has been renamed to 'String'

**Comment by gfontenot** [comment]
Yeah, this project hasn't been fully updated to support Swift 2.0 because with the advent of `indirect`, it's not that useful. There is an issue (#26) about needing to update the documentation to reflect this. I don't actually think that there are any Swift 2 compatible libraries using Box as a dependency at this point, either.

Would either of you be interested in opening a PR to flesh out the Swift 2.0 support?

**Comment by philipengberg** [comment]
The [newest version of ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v3.0.0) as a cocoapod has a dependency to Box, which is what caused this error for me.

**Comment by philipengberg** [comment]
Verstion 3.0.0 of ReactiveCocoa only uses Swift 1.2, but I guess that since my base SDK is iOS 9, Xcode tries to compile it as Swift 2?

**Comment by gfontenot** [comment]
That's because you're using Xcode 7. You'd need to use the `swift2` branch of RAC (or the 4.0 prerelease) to get Swift 2.0 support.

**Comment by philipengberg** [comment]
Yeah, but that's only in alpha. Don't feel comfortable using that in large scale production app :wink: It just seems weird that you are forced to use Swift 2 in Xcode 7. It basically makes ReactiveCocoa 3.0 useless.

**Comment by gfontenot** [comment]
>  It just seems weird that you are forced to use Swift 2 in Xcode 7

I agree. Unfortunately that's the world we live in.

**Comment by jrmsklar** [comment]
I'm seeing that same issue with ReactiveCocoa 3.0.

**Comment by neilpa** [comment]
@jrmsklar RAC 3 targets Swift 1.2 so this shouldn't be a problem. Unless you're trying to build RAC 3 w/ Xcode 7/Swift 2 which isn't going to work.

**Comment by philipengberg** [comment]
Which is exactly why I (and everybody else) is doing.

**Comment by neilpa** [comment]
What I'm saying is that RAC 3 won't ever build with Xcode 7 because Swift 2 has lots of breaking changes. You have to use the recently tagged RAC 4 alpha if you want to use Swift 2/Xcode 7.

**Comment by philipengberg** [comment]
Yes, I am completely aware of that by now, but that does not change the fact that RAC 3 is unusable to anyone who has to support iOS 9 actively.

**Comment by neilpa** [comment]
Supporting iOS 9 devices doesn't require building with the latest tools and SDKs. Apps built against the iOS 8 SDK with Xcode 6.4 run just fine on iOS 9. If you want to be on the latest tooling you have to expect some libraries will lag behind.

**Comment by neilpa** [comment]
Besides, there _is_ a supported version of RAC for Xcode 7. It's just not baked for long enough yet which is why it's still labelled as an alpha build.

**Comment by philipengberg** [comment]
Again, I **know**. But as I said, if you **actively** have to support iOS 9 specific features all you can do is use RAC 2.5 and hope that Apple will not make make as many syntactic breaking changes to the next version of Swift, so that third party libraries don't have to play as much catch up. Otherwise people will be stuck with old Obj-C libraries for the sake of syntactic sugar and language features.

**Comment by robrix** [comment]
Leaving aside the question of what one might want this for, I’d be more than happy to accept a PR updating `Box` to Swift 2.0.

**Comment by bavarious** [comment]
@robrix As far as I understand this issue, commits https://github.com/robrix/Box/commit/f152f1111daf1ab3700d25ddb59c310ea5e5b204 and https://github.com/robrix/Box/commit/e633c9740bac2bf152217d31fad9fa0886d4835a should already fix this problem. Those commits were checked in after the latest Box release (1.2.2) tag, though, so they are effectively ignored by Carthage. A new release/tag should make everybody happy.

**Comment by jrmsklar** [comment]
@neilpa, I'm trying to build for iOS 9 using Xcode 7, which as @philipengberg pointed out is not supported by the latest version of RAC.

**Comment by robrix** [comment]
@bavarious :+1: thanks.

**Comment by jlhonora** [comment]
+1 for a new release tag!

**Comment by robrix** [comment]
[Tagged 2.0](https://github.com/robrix/Box/releases/tag/2.0).
